name: Check HTML Formatting

on:
  push:
    paths:
      - '_includes/**/*.html'
  pull_request:
    paths:
      - '_includes/**/*.html'

jobs:
  prettier:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Prettier
        run: npm install -g prettier
        
      - name: Check Prettier formatting
        run: prettier --check "_includes/**/*.html"
